      - name: Commit dan Push Hasil Mapping
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # 1. Tandai file yang berubah
          git add playlist_termapping.m3u
          
          # 2. Simpan dulu perubahannya di lokal (Commit)
          # '|| echo' agar tidak eror jika tidak ada perubahan data
          git commit -m "Auto-update: M3U Bakul Wifi Sports Terbaru" || exit 0
          
          # 3. Baru tarik update terbaru dari GitHub (Pull Rebase)
          # Sekarang posisi index sudah bersih, jadi tidak akan eror lagi
          git pull origin main --rebase
          
          # 4. Terakhir, kirim semuanya (Push)
          git push origin main
