name: Update EPG Mapping

on:
  schedule:
    # Berjalan otomatis setiap hari pada jam 00:00 UTC (07:00 WIB)
    - cron: '0 0 * * *'
  workflow_dispatch: # Memungkinkan Anda menekan tombol "Run workflow" secara manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Jalankan Skrip Integrasi EPG
        run: python integrasi_epg.py

      - name: Commit dan Push Hasil Mapping
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add hasil_mapping_epg.txt
          # Hanya commit jika ada perubahan data
          git commit -m "Auto-update: Pembaruan mapping EPG" || echo "Tidak ada perubahan mapping baru"
          git push
